spring:
  datasource:
    url: jdbc:mysql://localhost/bd-SmartCity-grupo15
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect